/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eozmtutofshotfookohf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvem10dXRvZnNob3Rmb29rb2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTQ4NjgsImV4cCI6MjA5MTMzMDg2OH0.mbD0-_MRPuVyOLK5GUIzRiXVc_Lr6Vc-I2Vog1ZF4Ic"